repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.40.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
        entry: ggshield secret scan pre-commit
        verbose: true 